# Generated by Django 5.2.17 on 2026-08-30 13:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companysettings'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('total_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half day'), ('LEAVE', 'Leave'), ('HOLIDAY', 'Holiday'), ('WEEKEND', 'Weekend')], db_index=True, max_length=16)),
                ('check_in_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('check_out_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'ordering': ('-date', '-check_in'),
                'indexes': [models.Index(fields=['company', 'date'], name='attendance__company_afcfe3_idx'), models.Index(fields=['company', 'status', 'date'], name='attendance__company_3b2d38_idx'), models.Index(fields=['employee', 'date'], name='attendance__employe_08d913_idx'), models.Index(fields=['company', 'check_in'], name='attendance__company_6f6285_idx'), models.Index(fields=['company', 'check_out'], name='attendance__company_ae8e9c_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'employee', 'date'), name='uniq_attendance_company_employee_date'), models.CheckConstraint(condition=models.Q(('check_out__isnull', True), ('check_in__isnull', True), ('check_out__gte', models.F('check_in')), _connector='OR'), name='attendance_checkout_not_before_checkin')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='companies.company')),
            ],
            options={
                'ordering': ('-date', 'name'),
                'indexes': [models.Index(fields=['company', 'date'], name='attendance__company_7b4347_idx'), models.Index(fields=['company', 'is_active', 'date'], name='attendance__company_efda2f_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'date'), name='uniq_holiday_company_date')],
            },
        ),
    ]
