# Generated by Django 5.2.17 on 2026-08-31 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('device_name', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_177c8a_idx'), models.Index(fields=['company'], name='notificatio_company_bfddbb_idx'), models.Index(fields=['is_active'], name='notificatio_is_acti_20bbb3_idx'), models.Index(fields=['company', 'user', 'is_active'], name='notificatio_company_c7e3b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LEAVE_SUBMITTED', 'Leave submitted'), ('LEAVE_APPROVED', 'Leave approved'), ('LEAVE_REJECTED', 'Leave rejected'), ('LEAVE_CANCELLED', 'Leave cancelled'), ('DEVICE_ASSIGNED', 'Device assigned'), ('DEVICE_RETURNED', 'Device returned'), ('ATTENDANCE_REMINDER', 'Attendance reminder'), ('ATTENDANCE_LATE', 'Attendance late'), ('DOCUMENT_EXPIRING', 'Document expiring'), ('SYSTEM', 'System')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=2000)),
                ('entity_type', models.CharField(blank=True, choices=[('leave_request', 'Leave request'), ('device', 'Device'), ('attendance', 'Attendance'), ('employee_document', 'Employee document')], max_length=32)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('event_key', models.CharField(blank=True, max_length=128)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['company'], name='notificatio_company_f5f320_idx'), models.Index(fields=['recipient'], name='notificatio_recipie_be3f1a_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx'), models.Index(fields=['type'], name='notificatio_type_ea918f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['company', 'recipient', 'is_read'], name='notificatio_company_6b8e11_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event_key__gt', '')), fields=('company', 'recipient', 'event_key'), name='uniq_notification_event_key')],
            },
        ),
    ]
