# Generated by Django 5.2.17 on 2026-09-01 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('EMPLOYEE_CREATED', 'Employee created'), ('EMPLOYEE_UPDATED', 'Employee updated'), ('EMPLOYEE_DEACTIVATED', 'Employee deactivated'), ('DEPARTMENT_CREATED', 'Department created'), ('DEPARTMENT_UPDATED', 'Department updated'), ('LEAVE_SUBMITTED', 'Leave submitted'), ('LEAVE_APPROVED', 'Leave approved'), ('LEAVE_REJECTED', 'Leave rejected'), ('LEAVE_CANCELLED', 'Leave cancelled'), ('DEVICE_ASSIGNED', 'Device assigned'), ('DEVICE_RETURNED', 'Device returned'), ('ROLE_CHANGED', 'Role changed'), ('PERMISSION_CHANGED', 'Permission changed'), ('SETTINGS_CHANGED', 'Settings changed')], max_length=32)),
                ('entity_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('DEPARTMENT', 'Department'), ('LEAVE_REQUEST', 'Leave request'), ('DEVICE', 'Device'), ('USER', 'User'), ('ROLE', 'Role'), ('COMPANY_SETTINGS', 'Company settings')], max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='companies.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['company', 'created_at'], name='audit_logs__company_83ad73_idx'), models.Index(fields=['company', 'action'], name='audit_logs__company_0ba269_idx'), models.Index(fields=['company', 'entity_type'], name='audit_logs__company_88be6a_idx'), models.Index(fields=['company', 'user'], name='audit_logs__company_7010ec_idx'), models.Index(fields=['company', 'entity_type', 'entity_id'], name='audit_logs__company_5d7117_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['EMPLOYEE_CREATED', 'EMPLOYEE_UPDATED', 'EMPLOYEE_DEACTIVATED', 'DEPARTMENT_CREATED', 'DEPARTMENT_UPDATED', 'LEAVE_SUBMITTED', 'LEAVE_APPROVED', 'LEAVE_REJECTED', 'LEAVE_CANCELLED', 'DEVICE_ASSIGNED', 'DEVICE_RETURNED', 'ROLE_CHANGED', 'PERMISSION_CHANGED', 'SETTINGS_CHANGED'])), name='audit_log_valid_action'), models.CheckConstraint(condition=models.Q(('entity_type__in', ['EMPLOYEE', 'DEPARTMENT', 'LEAVE_REQUEST', 'DEVICE', 'USER', 'ROLE', 'COMPANY_SETTINGS'])), name='audit_log_valid_entity_type')],
            },
        ),
    ]
