// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSgEIpi2hvQ7aH3Cvmy1vQqoIXgEqpIls',
    appId: '1:193428864437:web:37259eae0c27b79becedfc',
    messagingSenderId: '193428864437',
    projectId: 'punjab-job-center',
    authDomain: 'punjab-job-center.firebaseapp.com',
    storageBucket: 'punjab-job-center.appspot.com',
    measurementId: 'G-EH8SS84QWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeslZg42Hd17A9D0Cqway22Fy8dzv6-BI',
    appId: '1:593068160415:android:ebb01eaf55b519442af9aa',
    messagingSenderId: '593068160415',
    projectId: 'punjab-job-center-c118c',
    storageBucket: 'punjab-job-center-c118c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACVu2QO6x78oeu-IlgX-8kVgbHAgSbTP0',
    appId: '1:593068160415:ios:306c6f02104ed55b2af9aa',
    messagingSenderId: '593068160415',
    projectId: 'punjab-job-center-c118c',
    storageBucket: 'punjab-job-center-c118c.appspot.com',
    iosClientId: '593068160415-dbitbshthbffdubjq5ck3p2c0upsvopv.apps.googleusercontent.com',
    iosBundleId: 'PITB.job-center',
  );
}
