# Generated by Django 5.2.17 on 2026-08-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(db_index=True, max_length=32)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], db_index=True, default='EMPLOYEE', help_text='Platform SUPER_ADMIN lives here. Company roles are stored on CompanyMembership; this field is kept for Django admin and users without a membership.', max_length=32),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('scope', models.CharField(choices=[('PLATFORM', 'Platform'), ('COMPANY', 'Company')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.permission')),
            ],
            options={
                'ordering': ('scope', 'code'),
                'constraints': [models.UniqueConstraint(fields=('code', 'scope'), name='uniq_role_code_scope')],
            },
        ),
    ]
