# Generated by Django 5.2.17 on 2026-08-31 16:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companysettings'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('manufacturer', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired'), ('LOST', 'Lost')], db_index=True, default='AVAILABLE', max_length=16)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='companies.company')),
            ],
            options={
                'ordering': ('asset_code',),
            },
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(db_index=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('condition_on_assignment', models.TextField(blank=True, max_length=2000)),
                ('condition_on_return', models.TextField(blank=True, max_length=2000)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to='companies.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='devices.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_assignments', to='employees.employee')),
            ],
            options={
                'ordering': ('-assigned_at', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company'], name='devices_dev_company_222622_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='devices_dev_status_bbf58f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['type'], name='devices_dev_type_274df7_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['asset_code'], name='devices_dev_asset_c_9d13cb_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='devices_dev_serial__4a3e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', 'status'], name='devices_dev_company_c2b2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', 'asset_code'], name='devices_dev_company_f1a302_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('company', 'asset_code'), name='uniq_device_company_asset_code'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number__isnull', False)), fields=('company', 'serial_number'), name='uniq_device_company_serial_number'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='device_cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('warranty_expiry__isnull', True), ('purchase_date__isnull', True), ('warranty_expiry__gte', models.F('purchase_date')), _connector='OR'), name='device_warranty_on_or_after_purchase'),
        ),
        migrations.AddIndex(
            model_name='deviceassignment',
            index=models.Index(fields=['device'], name='devices_dev_device__213864_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceassignment',
            index=models.Index(fields=['employee'], name='devices_dev_employe_39f5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceassignment',
            index=models.Index(fields=['assigned_at'], name='devices_dev_assigne_0f425a_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceassignment',
            index=models.Index(fields=['returned_at'], name='devices_dev_returne_ecf49e_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceassignment',
            index=models.Index(fields=['device', 'returned_at'], name='devices_dev_device__fe97d1_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceassignment',
            index=models.Index(fields=['company', 'device'], name='devices_dev_company_29c91a_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('device',), name='uniq_deviceassignment_active_device'),
        ),
        migrations.AddConstraint(
            model_name='deviceassignment',
            constraint=models.CheckConstraint(condition=models.Q(('returned_at__isnull', True), ('returned_at__gte', models.F('assigned_at')), _connector='OR'), name='deviceassignment_return_on_or_after_assign'),
        ),
    ]
