# Generated by Django 5.2.17 on 2026-08-30 13:45

import apps.companies.models
import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone used for attendance dates and work-hour rules.', max_length=64)),
                ('work_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('work_end_time', models.TimeField(default=datetime.time(18, 0))),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('minimum_working_minutes', models.PositiveIntegerField(default=480)),
                ('overtime_enabled', models.BooleanField(default=False)),
                ('working_days', models.JSONField(default=apps.companies.models.default_working_days)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.company')),
            ],
            options={
                'verbose_name': 'company settings',
                'verbose_name_plural': 'company settings',
            },
        ),
    ]
