# Generated by Django 5.2.17 on 2026-09-01 20:17

import apps.companies.constants
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=apps.companies.constants.settings_logo_path, validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'webp'))]),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='grace_period_minutes',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='minimum_working_minutes',
            field=models.PositiveIntegerField(default=480, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='timezone',
            field=models.CharField(default=apps.companies.constants.default_timezone, help_text='IANA timezone used for attendance dates and work-hour rules.', max_length=64),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='work_end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
    ]
