# Generated by Django 5.2.17 on 2026-08-31 18:05

import apps.documents.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_companysettings'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('CNIC', 'CNIC'), ('PASSPORT', 'Passport'), ('CONTRACT', 'Contract'), ('OFFER_LETTER', 'Offer letter'), ('RESUME', 'Resume'), ('EDUCATION_CERTIFICATE', 'Education certificate'), ('EXPERIENCE_LETTER', 'Experience letter'), ('BANK_DOCUMENT', 'Bank document'), ('TAX_DOCUMENT', 'Tax document'), ('MEDICAL_DOCUMENT', 'Medical document'), ('IDENTITY_DOCUMENT', 'Identity document'), ('OTHER', 'Other')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(('pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png')), apps.documents.models.validate_employee_document_file])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=16)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['company'], name='documents_e_company_d19c89_idx'), models.Index(fields=['employee'], name='documents_e_employe_b3deae_idx'), models.Index(fields=['document_type'], name='documents_e_documen_d06ff8_idx'), models.Index(fields=['status'], name='documents_e_status_3e4b0d_idx'), models.Index(fields=['expiry_date'], name='documents_e_expiry__73fa2f_idx'), models.Index(fields=['company', 'employee'], name='documents_e_company_f13263_idx'), models.Index(fields=['company', 'document_type'], name='documents_e_company_1bd39d_idx'), models.Index(fields=['company', 'status'], name='documents_e_company_44c953_idx')],
            },
        ),
    ]
