# Generated by Django 5.2.17 on 2026-09-01 21:41

import apps.documents.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('CNIC', 'CNIC'), ('PASSPORT', 'Passport'), ('CONTRACT', 'Contract'), ('OFFER_LETTER', 'Offer letter'), ('RESUME', 'Resume'), ('EDUCATION_CERTIFICATE', 'Education certificate'), ('EDUCATION', 'Education'), ('EXPERIENCE_LETTER', 'Experience letter'), ('EXPERIENCE', 'Experience'), ('CERTIFICATE', 'Certificate'), ('SALARY_DOCUMENT', 'Salary document'), ('BANK_DOCUMENT', 'Bank document'), ('TAX_DOCUMENT', 'Tax document'), ('MEDICAL_DOCUMENT', 'Medical document'), ('IDENTITY_DOCUMENT', 'Identity document'), ('OTHER', 'Other')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to=apps.documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(('pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png')), apps.documents.models.validate_employee_document_file]),
        ),
    ]
