# Generated by Django 5.2.17 on 2026-09-01 21:48

import apps.documents.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_employeedocument_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(max_length=512, upload_to=apps.documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(('pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png')), apps.documents.models.validate_employee_document_file]),
        ),
    ]
