# Generated by Django 5.2.17 on 2026-09-01 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companysettings'),
        ('employees', '0001_initial'),
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['company', 'start_date'], name='leave_leave_company_0c3b1d_idx'),
        ),
    ]
