# Generated by Django 5.2.17 on 2026-09-01 21:48

import apps.leave.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_report_query_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=apps.leave.models.leave_attachment_path, validators=[django.core.validators.FileExtensionValidator(('pdf', 'png', 'jpg', 'jpeg', 'webp', 'doc', 'docx')), apps.leave.models.validate_leave_attachment]),
        ),
    ]
